# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/dora
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: dora.eof-devnet-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  name: eof-devnet-0
  configPath: "https://config.eof-devnet-0.ethpandaops.io/cl/config.yaml"
  validatorNamesInventory: "https://config.eof-devnet-0.ethpandaops.io/api/v1/nodes/validator-ranges"
  proxyCount: 2
  extraEnv:
    - name: FRONTEND_PPROF
      value: "true"
    - name: FRONTEND_SHOW_SENSITIVE_PEER_INFOS
      value: "true"
    - name: FRONTEND_ETH_EXPLORER_LINK
      value: "https://explorer.eof-devnet-0.ethpandaops.io"
    - name: FRONTEND_PUBLIC_RPC_URL
      value: "https://rpc.eof-devnet-0.ethpandaops.io"
    - name: FRONTEND_SHOW_SUBMIT_DEPOSIT
      value: "true"
    - name: FRONTEND_SHOW_SUBMIT_EL_REQUESTS
      value: "true"
  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"

  endpoints:
  # Rpc
  - url: http://prysm-geth-001:5052
    name: rpc-prysm-geth-001
    archive: true
    priority: 1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@bn.bootnode-1.eof-devnet-0.ethpandaops.io
    name: bootnode-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@bn.prysm-besu-1.eof-devnet-0.ethpandaops.io
    name: prysm-besu-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@bn.prysm-besu-2.eof-devnet-0.ethpandaops.io
    name: prysm-besu-2
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@bn.prysm-geth-1.eof-devnet-0.ethpandaops.io
    name: prysm-geth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@bn.prysm-geth-2.eof-devnet-0.ethpandaops.io
    name: prysm-geth-2
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@bn.prysm-nethermind-1.eof-devnet-0.ethpandaops.io
    name: prysm-nethermind-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@bn.prysm-reth-1.eof-devnet-0.ethpandaops.io
    name: prysm-reth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@bn.prysm-reth-2.eof-devnet-0.ethpandaops.io
    name: prysm-reth-2
    priority: -1
  executionEndpoints:
  # Rpc
  - url: http://geth-prysm-001:8545
    name: rpc-prysm-geth-001
    archive: true
    priority: 1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@rpc.bootnode-1.eof-devnet-0.ethpandaops.io
    name: bootnode-1
    priority: -1
    archive: false
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@rpc.prysm-besu-1.eof-devnet-0.ethpandaops.io
    name: prysm-besu-1
    priority: -1
    archive: false
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@rpc.prysm-besu-2.eof-devnet-0.ethpandaops.io
    name: prysm-besu-2
    priority: -1
    archive: false
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@rpc.prysm-geth-1.eof-devnet-0.ethpandaops.io
    name: prysm-geth-1
    priority: -1
    archive: false
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@rpc.prysm-geth-2.eof-devnet-0.ethpandaops.io
    name: prysm-geth-2
    priority: -1
    archive: false
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@rpc.prysm-nethermind-1.eof-devnet-0.ethpandaops.io
    name: prysm-nethermind-1
    priority: -1
    archive: false
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@rpc.prysm-reth-1.eof-devnet-0.ethpandaops.io
    name: prysm-reth-1
    priority: -1
    archive: false
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.eof-devnets.node_ingress.combined}>@rpc.prysm-reth-2.eof-devnet-0.ethpandaops.io
    name: prysm-reth-2
    priority: -1
    archive: false
